### ISSUE TITLE
Figure out how to run ruby builds on Docker

### ISSUE THREAD

**Issue by skierkowski** [factor-io/ephemeral#6]
For the scenario we want to be able to take a repo and run a build on it, then get the results. For the sake of figuring out the implementation we should figure out how to do this manually today using a 3rd party service.

So given the [skierkowski/hello-middleman](https://github.com/skierkowski/hello-middleman) repo you should be able to `git clone`, `bundle install` and `bundle exec middleman build` today from the command-line.  We basically want to replicate that entire process on a local instance of Docker.

Docker provides a set of images designed to bootstrap a build environment (e.g. installing Ruby) and then using that environment to build an application, this is called [Buildpack-deps](https://registry.hub.docker.com/_/buildpack-deps/).

For this exercise we should use the [Ruby buildpack](https://github.com/docker-library/docs/tree/master/ruby) to run the `bundle exec middleman build` command in Docker.

**Comment by skierkowski** [comment]
I got this working. Assuming you have the latest boo2docker and docker installed you can just do this...

    git clone git@github.com:skierkowski/hello-middleman
    cd middleman
    $(boot2docker shellinit)
    docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app ruby:2.1 sh -c 'apt-get update && apt-get install -y nodejs --no-install-recommends && bundle install && bundle exec middleman build'

This last command is very long, so let me explain. The `--rm` options removes all the contents after running that container. `-v` option mounts a local directory inside of the container, in this case it maps the current directory (as identified by $PWD) to `/usr/src/app`. The `-w` options sets the working directory to the location of the mounted directory (our current working directory).  `ruby:2.1` tells which image to use for the docker container. The last piece runs the command that you want in docker.

In this case `sh -c` runs another shell command, and the -c specifies the commands we want to run. Normally you wouldn't launch a shell in a shell, but in this case we need to do that because we need to run a set of commands, not just one. If we ran just one command we wouldn't need this piece.

Lastly it runs these set of commands in the container. The first two install nodejs. Node JS is actually required by Middleman (and Rails for that matter) in order to compile some of the javascript. The last two commands run bundler and run the middleman command.
apt-get update
apt-get install -y nodejs --no-install-recommends
bundle install
bundle exec middleman build

**Comment by clemf** [comment]
We both got this running, although I think Joey and I are still getting the hang of how Docker works. The first thing we noticed is that the version of middleman in the middleman-hello project doesn't build under Ruby 2.2. We got it working with 2.1.

What exactly does `$(boot2docker shellinit)` do, and why does it need to be inside dollarsign parens?

`--rm` deletes the container immediately after running, right? Is that just so we don't leave a bunch of crusty containers behind?

**Comment by skierkowski** [comment]
Yes, on `--rm`.

if you just run `boot2docker shellinit` you'll notice that it just output commands to set environment variables. But it just displays them, it doesn't actually set them. By wrapping it in `$()` it sends the output of that command as if you ran it yourself, thus, setting the environment variables. As such, you only need to run that command when you start a new shell. 

Having said that, I wouldn't necessarily ad dit to your `.bash_profile` because that command will fail if the VM running docker hasn't started. So boot2docker needs to be running first. When I develop I typically have two to four shells open at once and I only do docker stuff in one. So I just run `$(boot2docker shellinit)` once.

**Comment by skierkowski** [comment]
Closing per the notes I made earlier.
