### ISSUE TITLE
Build a gist which is able to run a build in Tutum

### ISSUE THREAD

**Issue by skierkowski** [factor-io/ephemeral#7]
Using Tutum, run `git clone git@github.com:skierkowski/hello-middleman`, `bundle install` and `bundle exec middleman build` using nothing but a single ruby file.

This will demonstrate the functionality that will be required in the worker.

**Comment by clemf** [comment]
It looks like we need to first have a cloud provider before we can use Tutum.

**Comment by skierkowski** [comment]
Use digitalocean.com, you can setup a server for $5/mo.

**Comment by skierkowski** [comment]
https://gist.github.com/skierkowski/c2f9e2a16f6c1760b607
