### ISSUE TITLE
Run a middleman build in Tutum using docker-deps

### ISSUE THREAD

**Issue by skierkowski** [factor-io/ephemeral#8]
Do the same thing as #6 but instead of using your local Docker server use Tutum.

**Comment by clemf** [comment]
We've been trying to figure out Tutum all day but no luck getting the code to run so far. I think it's hard to understand how Tutum works when we're only just getting the hang of Docker.

**Comment by skierkowski** [comment]
In that case there might be two things you could do first to learn: (1) build your own hello world app and run it on Docker using your own Dockerfile, and (2) figuring out how to run it on Tutum. Once you have that, you just need to combine the previous work with the building of middleman and this to get it to run on Tutum.

... Or, if you guys have the time we could do it together in the afternoon tomorrow or Friday AM.

**Comment by clemf** [comment]
I'll keep hacking away, but I think meeting up tomorrow would be great.

**Comment by skierkowski** [comment]
https://gist.github.com/skierkowski/c2f9e2a16f6c1760b607

BOOM!
